#!/usr/bin/env bash
# noctalia-sync.sh — Bridge omarchy colors.toml → Noctalia theme.toml
# Installed to: ~/.config/omarchy/hooks/theme-set.d/
# Triggered automatically by omarchy-theme-set after every theme change.
#
# Reads omarchy's current colors.toml and generates a TOML theme file
# for Noctalia at ~/.config/noctalia/theme.toml.
# Includes wallpaper sync if the theme ships a backgrounds/ directory.
# Set NOCTALIA_SYNC_NO_WALLPAPER=1 to skip wallpaper sync.

set -euo pipefail

THEME_DIR="${OMARCHY_CURRENT_THEME:-$HOME/.local/state/omarchy/current/theme}"
NOCTALIA_DIR="$HOME/.config/noctalia"
NOCTALIA_THEME="$NOCTALIA_DIR/theme.toml"

if [[ ! -f "$THEME_DIR/colors.toml" ]]; then
  echo "noctalia-sync: no colors.toml found at $THEME_DIR" >&2
  exit 1
fi

mkdir -p "$NOCTALIA_DIR"

THEME_NAME_FILE="$HOME/.local/state/omarchy/current/theme.name"
if [[ -f "$THEME_NAME_FILE" ]]; then
  THEME_NAME=$(<"$THEME_NAME_FILE")
else
  THEME_NAME=$(basename "$THEME_DIR")
fi

export NOCTARCHIA_THEME_DIR="$THEME_DIR"
export NOCTARCHIA_THEME_NAME="$THEME_NAME"
export NOCTARCHIA_NOCTALIA_DIR="$NOCTALIA_DIR"

python3 <<'PYEOF'
import os
import tomllib
from pathlib import Path

theme_dir = Path(os.environ["NOCTARCHIA_THEME_DIR"])
theme_name = os.environ["NOCTARCHIA_THEME_NAME"]
noctalia_dir = Path(os.environ["NOCTARCHIA_NOCTALIA_DIR"])

data = tomllib.loads((theme_dir / "colors.toml").read_text())
mode = data.get("mode", "dark")


def hex_color(key, fallback):
    v = data.get(key)
    if isinstance(v, str) and len(v) >= 6:
        return "#" + v.lstrip("#")[:6]
    return "#" + fallback


accent          = hex_color("accent",           "888888")
background      = hex_color("background",       "111111")
dark_background = hex_color("dark_background",  "1a1a1a")
darker_bg       = hex_color("darker_background","0a0a0a")
lighter_bg      = hex_color("lighter_background","333333")
foreground      = hex_color("foreground",       "cccccc")
dark_foreground = hex_color("dark_foreground",  "444444")
muted           = hex_color("muted",            "666666")
selection       = hex_color("selection",        "222222")
red             = hex_color("red",              "ff4444")
yellow          = hex_color("yellow",           "aaaa44")
green           = hex_color("green",            "44aa44")
cyan            = hex_color("cyan",             "44aaaa")
blue            = hex_color("blue",             "4444ff")
magenta         = hex_color("magenta",          "aa44aa")
bright_red      = hex_color("bright_red",       "ff6666")
bright_yellow   = hex_color("bright_yellow",    "cccc66")
bright_green    = hex_color("bright_green",     "66cc66")
bright_cyan     = hex_color("bright_cyan",      "66cccc")
bright_blue     = hex_color("bright_blue",      "6666ff")
bright_magenta  = hex_color("bright_magenta",   "cc66cc")
bright_fg       = hex_color("bright_foreground","eeeeee")

lines = [
    "# Noctalia theme — auto-generated by noctalia-sync.sh",
    "# Do not edit manually; changes are overwritten on theme change.",
    "",
    f"name = \"{theme_name}\"",
    f"mode = \"{mode}\"",
    "",
    "[palette]",
    f"accent           = \"{accent}\"",
    f"background       = \"{background}\"",
    f"dark_background  = \"{dark_background}\"",
    f"darker_background= \"{darker_bg}\"",
    f"lighter_background=\"{lighter_bg}\"",
    f"foreground       = \"{foreground}\"",
    f"dark_foreground  = \"{dark_foreground}\"",
    f"muted            = \"{muted}\"",
    f"selection        = \"{selection}\"",
    "",
    f"red              = \"{red}\"",
    f"yellow           = \"{yellow}\"",
    f"green            = \"{green}\"",
    f"cyan             = \"{cyan}\"",
    f"blue             = \"{blue}\"",
    f"magenta          = \"{magenta}\"",
    "",
    f"bright_red       = \"{bright_red}\"",
    f"bright_yellow    = \"{bright_yellow}\"",
    f"bright_green     = \"{bright_green}\"",
    f"bright_cyan      = \"{bright_cyan}\"",
    f"bright_blue      = \"{bright_blue}\"",
    f"bright_magenta   = \"{bright_magenta}\"",
    f"bright_foreground= \"{bright_fg}\"",
]

(noctalia_dir / "theme.toml").write_text("\n".join(lines) + "\n")

# Wallpaper sync — write to noctalia's state if backgrounds dir exists.
if os.environ.get("NOCTALIA_SYNC_NO_WALLPAPER") != "1":
    wp_dir = theme_dir / "backgrounds"
    if wp_dir.is_dir():
        imgs = sorted(
            p for p in wp_dir.iterdir()
            if p.is_file() and p.suffix.lower() in {".jpg", ".jpeg", ".png", ".webp"}
        )
        pick = next(
            (p for p in imgs if theme_name.lower() in p.name.lower()),
            imgs[0] if imgs else None,
        )
        if pick:
            state_dir = Path.home() / ".local" / "state" / "noctalia" / "wallpaper"
            state_dir.mkdir(parents=True, exist_ok=True)
            target = pick.resolve()
            (state_dir / "path.txt").write_text(str(target) + "\n")
            cur = state_dir / "current"
            if cur.is_symlink() or cur.exists():
                cur.unlink()
            cur.symlink_to(target)

PYEOF

echo "noctalia-sync: synced theme '$THEME_NAME' → $NOCTALIA_THEME" >&2
