#!/usr/bin/env bash
# noctalia-sync.sh — Bridge omarchy colors.toml → Noctalia + Niri theme
# Installed to: ~/.config/omarchy/hooks/theme-set.d/
# Triggered automatically by omarchy-theme-set after every theme change.
#
# Reads omarchy's current colors.toml and:
#   1. Updates Noctalia config.toml accent colors
#   2. Updates Niri config.kdl border/focus ring colors
#   3. Generates Noctalia theme.toml as reference
#   4. Syncs wallpaper if the theme ships a backgrounds/ directory.

set -euo pipefail

THEME_DIR="${OMARCHY_CURRENT_THEME:-$HOME/.local/state/omarchy/current/theme}"
NOCTALIA_DIR="$HOME/.config/noctalia"
NOCTALIA_CFG="$NOCTALIA_DIR/config.toml"
NIRI_CFG="$HOME/.config/niri/config.kdl"

if [[ ! -f "$THEME_DIR/colors.toml" ]]; then
  echo "noctalia-sync: no colors.toml found at $THEME_DIR" >&2
  exit 1
fi

mkdir -p "$NOCTALIA_DIR"

THEME_NAME_FILE="$HOME/.local/state/omarchy/current/theme.name"
if [[ -f "$THEME_NAME_FILE" ]]; then
  THEME_NAME=$(<"$THEME_NAME_FILE")
else
  THEME_NAME=$(basename "$THEME_DIR")
fi

export OMARCHY_CURRENT_THEME="$THEME_DIR"
export NOCTARCHIA_THEME_NAME="$THEME_NAME"
export NOCTALIA_DIR
export NIRI_CFG

python3 <<'PYEOF'
import os
import re
import tomllib
from pathlib import Path

theme_dir = Path(os.environ["OMARCHY_CURRENT_THEME"] or Path.home() / ".local/state/omarchy/current/theme")
theme_name = os.environ.get("NOCTARCHIA_THEME_NAME", "unknown")
noctalia_dir = Path(os.environ["NOCTALIA_DIR"])
noctalia_cfg = noctalia_dir / "config.toml"
niri_cfg = Path(os.environ["NIRI_CFG"])

data = tomllib.loads((theme_dir / "colors.toml").read_text())

def hex_color(key, fallback):
    v = data.get(key)
    if isinstance(v, str) and len(v) >= 6:
        return "#" + v.lstrip("#")[:6]
    return "#" + fallback

accent          = hex_color("accent",           "7c3aed")
background      = hex_color("background",       "1a1a2e")
dark_background = hex_color("dark_background",  "11111b")
foreground      = hex_color("foreground",       "c0d0e0")
muted           = hex_color("muted",            "586070")
bright_fg       = hex_color("bright_foreground", "eeeeee")
selection       = hex_color("selection",         "292e42")

# ── 1. Patch Noctalia config.toml ──
if noctalia_cfg.exists():
    cfg = noctalia_cfg.read_text()
    mode = data.get("mode", "dark")
    # Replace entire [theming] section
    theming_block = f"""[theming]
source = "wallpaper"
dark_mode = {"true" if mode == "dark" else "false"}
accent_color = "{accent}"
bg_color = "{background}"
text_color = "{foreground}"
border_color = "{muted}"
sel_bg_color = "{selection}"
border_radius = 12"""
    cfg = re.sub(r'\[theming\].*?(?=\n\[|\Z)', theming_block, cfg, flags=re.DOTALL)
    noctalia_cfg.write_text(cfg)
    print(f"noctalia-sync: patched config.toml accent={accent} bg={background} fg={foreground} border={muted}")

# ── 2. Patch Niri config.kdl borders ──
if niri_cfg.exists():
    kdl = niri_cfg.read_text()
    # Use word-boundary-like matching: active-color (not inactive-color)
    kdl = re.sub(r'(?<!\w)(active-color\s+)"#[0-9a-fA-F]{6}"', f'\\1"{accent}"', kdl)
    kdl = re.sub(r'(inactive-color\s+)"#[0-9a-fA-F]{6}"', f'\\1"{muted}"', kdl)
    niri_cfg.write_text(kdl)
    print(f"noctalia-sync: patched config.kdl borders accent={accent} inactive={muted}")

# ── 3. Generate theme.toml as reference ──
lines = [
    "# Noctalia theme — auto-generated by noctalia-sync.sh",
    f"# Source: {theme_name} / colors.toml",
    "",
    f"name = \"{theme_name}\"",
    f"mode = \"{data.get('mode', 'dark')}\"",
    "",
    "[palette]",
    f"accent           = \"{accent}\"",
    f"background       = \"{background}\"",
    f"foreground       = \"{foreground}\"",
    f"muted            = \"{muted}\"",
    f"bright_foreground= \"{bright_fg}\"",
]
(noctalia_dir / "theme.toml").write_text("\n".join(lines) + "\n")

# ── 4. Wallpaper sync ──
if os.environ.get("NOCTALIA_SYNC_NO_WALLPAPER") != "1":
    wp_dir = theme_dir / "backgrounds"
    if wp_dir.is_dir():
        imgs = sorted(
            p for p in wp_dir.iterdir()
            if p.is_file() and p.suffix.lower() in {".jpg", ".jpeg", ".png", ".webp"}
        )
        pick = next(
            (p for p in imgs if theme_name.lower() in p.name.lower()),
            imgs[0] if imgs else None,
        )
        if pick:
            state_dir = Path.home() / ".local" / "state" / "noctalia" / "wallpaper"
            state_dir.mkdir(parents=True, exist_ok=True)
            target = pick.resolve()
            (state_dir / "path.txt").write_text(str(target) + "\n")
            cur = state_dir / "current"
            if cur.is_symlink() or cur.exists():
                cur.unlink()
            cur.symlink_to(target)
            print(f"noctalia-sync: wallpaper → {target}")

print(f"noctalia-sync: synced theme '{theme_name}'")
PYEOF
